runtime: nodejs14
env_variables:
  SQL_USER: root
  SQL_PASSWORD: dayamsql
  SQL_DATABASE: daya_database
  INSTANCE_CONNECTION_NAME: daya-b21-cap0034:us-central1:dayamsql
beta_settings:
  cloud_sql_instances: daya-b21-cap0034:us-central1:dayamsql